version: '3'
services:
  flask:
    build: .
    restart: always
    ports:
      - 80:80
    environment:
      DATABASE_USER: admin
      DATABASE_PASSWORD: pass
      DATABASE_HOST: db
      DATABASE_NAME: db
    volumes:
      - ./src:/var/app/src
    depends_on:
      - db
  db:
    build:
      context: postgres
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: db
      POSTGRES_PASSWORD: pass
    volumes:
      - ./postgres/db_data:/var/lib/postgresql/data
#      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
volumes:
  src: {}
  db_data: {}
